console.log("typeof undefined : ", typeof undefined)
console.log("typeof null : ", typeof null)
console.log("undefined == null : ", undefined == null)
console.log("0 == null : ", 0 == null)
console.log("undefined == 0 : ", undefined == 0)
console.log("undefined === null: ", undefined === null)
console.log("0 === null: ", 0 === null)
console.log("undefined === 0: ", undefined === 0)
console.log("1 + null = ", 1 + null)
console.log("1 - null = ", 1 - null)
console.log("1 * null = ", 1 * null)
console.log("1 / null = ", 1 / null)

